### ISSUE TITLE
Add F# Power Tools 

### ISSUE THREAD

**Issue by derwasp** [gusztavvargadr/vagrant#20]
Since F# is already a part of the installation, F# Power Tools extension is desired, because it's essential for F# development.

**Comment by gusztavvargadr** [comment]
@derwasp thanks for reporting the issue, will be added in the next (first) release.

**Comment by gusztavvargadr** [comment]
Obsolete with #39 in favor of https://github.com/gusztavvargadr/workstations/issues/3.
