### ISSUE TITLE
Add Windows Server 2016 workstation

### ISSUE THREAD

**Issue by derwasp** [gusztavvargadr/vagrant#24]
Add a workstation which allows developing .NET application with Docker.

Windows 10 workstations can only work with Docker via Hyper-V and nested virtualization is not supported by virtualbox. So, since the only version of Windows, which has native Docker support is Windows Server 2016, it should be it.

Related to #13

**Comment by gusztavvargadr** [comment]
@derwasp thanks for reporting the issue, this might take some more time, as it needs a new base box with Packer. Until then, you might want to try experimenting the base box I used in the playground https://github.com/gusztavvargadr/vagrant/tree/master/src/playground/windows.

**Comment by gusztavvargadr** [comment]
@derwasp FYI this is coming soon https://github.com/gusztavvargadr/packer/milestone/8

**Comment by gusztavvargadr** [comment]
Windows Server 2016-based boxes are now available at https://atlas.hashicorp.com/gusztavvargadr/.

**Comment by gusztavvargadr** [comment]
Implemented in https://github.com/gusztavvargadr/workstations/issues/3.
