### ISSUE TITLE
Increase workstations RAM to at least 4gb

### ISSUE THREAD

**Issue by derwasp** [gusztavvargadr/vagrant#38]
Developing with Visual Studio with 2gb is a painful experience ;)

**Comment by gusztavvargadr** [comment]
@derwasp I agree, I have it increased in my personal configuration too: https://github.com/gusztavvargadr/vagrant/blob/d16f8164c079ec88cf7bb172df69fb102c142954/src/workstations/vagrant.custom.yml :)

Did you mean increasing it by default? Just wanted to double check if you are aware of the various [customization options](https://github.com/gusztavvargadr/vagrant/tree/master/samples#customization).

I can imagine scenarios (e.g. running only [powershell commands](https://www.vagrantup.com/docs/cli/powershell.html) for building) without the need of rdp so less memory can be suitable, but for that probably not a workstation like this is the most optimal setup, so I'm open for increasing it by default if that's what you meant.

**Comment by derwasp** [comment]
@gusztavvargadr I am sorry for not being clear about it. Yes, I meant by default of course.
And yes, I do know about the customization options, it's just I think having more memory by default is more general case here ;)

**Comment by gusztavvargadr** [comment]
Implemented in https://github.com/gusztavvargadr/workstations/issues/3. Defaults are now 2 cpus with 4 GB of memory.
